// Generated by CoffeeScript 1.9.1
var draw_orgchart;

draw_orgchart = function() {
  var add_more_genotypes, add_more_phenotypes, animation_duration, bgcolor, colors, div, h, svg, w, xs, ys;
  h = 600;
  w = 900;
  colors = ["#7442c8", "#c364c5", "#a8e4a0", "#fd7c6e"];
  bgcolor = "#181818";
  xs = d3.scale.linear().range([0, w]).domain([0, 100]);
  ys = d3.scale.linear().range([0, h]).domain([0, 100]);
  animation_duration = 1000;
  div = d3.select("div#orgchart");
  svg = div.append("svg").attr("height", h).attr("width", w).attr("id", "orgchart");
  svg.append("rect").attr("x", xs(0)).attr("y", ys(0)).attr("width", xs(25)).attr("height", ys(33)).attr("stroke", bgcolor).attr("stroke-width", 1).attr("fill", colors[0]).on("click", function() {
    return add_more_genotypes();
  });
  svg.append("text").attr("x", xs(12.5)).attr("y", ys(5)).text("genotypes").attr("fill", bgcolor).attr("dominant-baseline", "middle").attr("text-anchor", "middle").style("font-size", "30pt");
  svg.append("rect").attr("x", xs(29)).attr("y", ys(0)).attr("width", xs(30)).attr("height", ys(33)).attr("stroke", bgcolor).attr("stroke-width", 1).attr("fill", colors[1]).on("click", function() {
    return add_more_phenotypes();
  });
  svg.append("text").attr("x", xs(29 + 15)).attr("y", ys(5)).text("phenotypes").attr("fill", bgcolor).attr("dominant-baseline", "middle").attr("text-anchor", "middle").style("font-size", "30pt");
  add_more_genotypes = function() {
    var x;
    x = [34, 68];
    svg.selectAll("empty").data(x).enter().append("rect").attr("x", xs(0)).attr("y", function(d) {
      return ys(d);
    }).attr("width", xs(25)).attr("height", ys(33)).attr("stroke", bgcolor).attr("stroke-width", 1).attr("fill", colors[0]).attr("opacity", 0).transition().duration(animation_duration).delay(function(d, i) {
      return i * animation_duration;
    }).attr("opacity", 1);
    x = [34, 68];
    return svg.selectAll("empty").data(x).enter().append("rect").attr("x", xs(29)).attr("y", function(d) {
      return ys(d);
    }).attr("width", xs(30)).attr("height", ys(33)).attr("stroke", bgcolor).attr("stroke-width", 1).attr("fill", colors[1]).attr("opacity", 0).transition().duration(animation_duration).delay(function(d, i) {
      return i * animation_duration;
    }).attr("opacity", 1);
  };
  return add_more_phenotypes = function() {
    var col, wid, x, y;
    x = [60, 60, 60, 71, 71, 71];
    y = [0, 34, 68, 0, 34, 68];
    wid = [10, 10, 10, 30, 30, 30];
    col = [colors[2], colors[2], colors[2], colors[3], colors[3], colors[3]];
    return svg.selectAll("empty").data(x).enter().append("rect").attr("x", function(d) {
      return xs(d);
    }).attr("y", function(d, i) {
      return ys(y[i]);
    }).attr("width", function(d, i) {
      return xs(wid[i]);
    }).attr("height", ys(33)).attr("stroke", bgcolor).attr("stroke-width", 1).attr("fill", function(d, i) {
      return col[i];
    }).attr("opacity", 0).transition().duration(animation_duration).delay(function(d, i) {
      return i * animation_duration / 2;
    }).attr("opacity", 1);
  };
};

draw_orgchart();
